{% set name = "pyfolio-reloaded" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: ad9dc043ecfbe3eaaa80a2277f90788f

build:
  number: 0
  skip: true # [py<37 or not x86_64]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipython >=3.2.3
    - matplotlib >=1.4.0
    - numpy >=1.11.1
    - pandas >=0.18.1
    - pytz >=2014.10
    - scipy >=0.14.0
    - scikit-learn>=0.16.1
    - seaborn >=0.7.1
    - empyrical-reloaded >=0.5.7 # pending update

test:
  imports:
    - pyfolio

about:
  home: https://pyfolio.ml4trading.io
  summary: pyfolio is a Python library for performance and risk analysis of financial portfolios
  license: Apache 2.0
  license_file: LICENSE
